apiVersion: v1
kind: Service
metadata:
  name: {{ include "rayserver.service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rayserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rayserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
